server:
  port: 8083
  context-path: /springBoot-SOAP-client
it:
  myst:
    test:
      wsdl:
        flight:
          client:
            generatePackage: it.myst.test.wsdl.airport.client2
            defaultUri: http://www.webservicex.net/airport.asmx
spring:
  application:
    name: springBoot-SOAP-client
logging:
  file: ./target/springBoot-SOAP-client.log