server:
  port: 8080
  context-path: /springBoot-SOAP-client
it:
  soap:
    test:
      def:
        wsdl:
          client:
            generatePackage: it.fi.soap.test.def.wsdl
          server:
            defaultUri: http://172.17.0.1:8082/springBoot-SOAP-server/ws/calculatorDef.wsdl
spring:
  application:
    name: springBoot-SOAP-client
logging:
  file: ./target/springBoot-SOAP-client.log