server:
  port: 8080
  context-path: /springBoot-SOAP-client
it:
  soap:
    test:
      def:
        wsdl:
          client:
            generatePackage: it.fi.soap.test.def.wsdl
          server:
            defaultHost: 172.17.0.1:8082
            defaultUriPath: /springBoot-SOAP-server/ws/calculatorDef.wsdl
            envHost:
            #envHost: ${SOAP_SERVER_HOST}
spring:
  application:
    name: springBoot-SOAP-client
logging:
  file: ./target/springBoot-SOAP-client.log