
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.fi.soap.test.def.wsdl.newservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * Generated source version: 3.4.2
 *
 */

@javax.jws.WebService(
                      serviceName = "AirService",
                      portName = "AirServiceSoap",
                      targetNamespace = "http://airservice.wsdl.def.test.soap.fi.it/airDef/",
                      wsdlLocation = "file:/home/francesco/repositories/github/springBoot-SOAP-client-server/springBoot-SOAP-server/target/classes/wsdl/new-service/new-soap-service.wsdl",
                      endpointInterface = "it.fi.soap.test.def.wsdl.newservice.AirServiceSoap")

public class AirServiceSoapImpl implements AirServiceSoap {

    private static final Logger LOG = Logger.getLogger(AirServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see it.fi.soap.test.def.wsdl.newservice.AirServiceSoap#flightTimeCalculate(it.fi.soap.test.def.wsdl.newservice.FlightTimeRequest parameters)*
     */
    public it.fi.soap.test.def.wsdl.newservice.FlightTimeResponse flightTimeCalculate(FlightTimeRequest parameters) {
        LOG.info("Executing operation flightTimeCalculate");
        System.out.println(parameters);
        try {
            it.fi.soap.test.def.wsdl.newservice.FlightTimeResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
