package it.fi.soap.test.def.wsdl.newservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://airservice.wsdl.def.test.soap.fi.it/airDef/", name = "AirServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AirServiceSoap {

    @WebMethod(action = "http://airservice.wsdl.def.test.soap.fi.it/airDef/flightTimeCalculate")
    @WebResult(name = "FlightTimeResponse", targetNamespace = "http://airservice.wsdl.def.test.soap.fi.it/airDef/", partName = "parameters")
    public FlightTimeResponse flightTimeCalculate(

        @WebParam(partName = "parameters", name = "FlightTimeRequest", targetNamespace = "http://airservice.wsdl.def.test.soap.fi.it/airDef/")
        FlightTimeRequest parameters
    );
}
